# ten seconds should be enough to login from anywhere. even from a cruise ship via star-link (tested)
LoginGraceTime 10s

# if you don't know how to properly send your specified ssh key, get out.
MaxAuthTries 1

# you shall only use ssh keys
PasswordAuthentication no

# only ed25519 host key
HostKey /etc/ssh/ssh_host_ed25519_key

# archlinux sane defaults
KbdInteractiveAuthentication no
UsePAM yes
PrintMotd no
