# disable suspension of audio devices given by specified matches

monitor.alsa.rules = [
  {
    matches = [
      {
        # my usb in-ear dac has a startup ramp of roughly a second or two.
        # quite annoying if you want to pause, read, and continue listening.
        node.nick = "Hidizs ST2 PRO DAC"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
