set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",$TERM:RGB"
set -g mouse on
set-option -sg escape-time 10
set-option -g focus-events on

bind r source-file ~/.config/tmux/tmux.conf

set -g status-left-style 'fg=black bg=white'
set -g status-left '#{session_name}#{?session_many_attached,:#{session_attached},}'

#           
# 󰈈 󰎂 󱀅 󰓦 󰓹    󰨤 󰃃 󰛐 󱈸  󰝟

set -g status-right-style 'fg=black bg=red'
set -g status-right '%H:%M#[fg=red]#{?client_prefix,#[bg=yellow],#[bg=green]}#[fg=black]%d.%m.%Y'

set -g status-style 'fg=green bg=black'

set -g window-status-current-style 'fg=black bg=green'
set -g window-status-current-format '#I#W #{s/\*/󰎂 /:window_flags}'

set -g window-status-separator ''
set -g window-status-style 'fg=black bg=colour8'
set -g window-status-format '#{?window_bell_flag,#[bg=red],}#{?window_last_flag,#[bg=darkgreen],}#{?window_flags,#I,#[fg=white]#I#[fg=default]#[fg=white]}#W#{?window_flags, ,}#{?window_last_flag, ,}#{?window_marked_flag,󰃃 ,}#{?window_activity_flag, ,}#{?window_bell_flag, ,}#{?window_silence_flag,󰝟 ,}#{?window_zoomed_flag,󰨤 ,}#[fg=default]'
