set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'

TMUX_FZF_LAUNCH_KEY="C-f"

set -g history-limit 50000
set -g base-index 1
set -g pane-base-index 1
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",$TERM:RGB"
# set -ga terminal-overrides ",*256col*:Tc"
set -g mouse on
set-option -sg escape-time 10
set-option -g focus-events on
set-option -g renumber-windows on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g mode-keys vi
bind-key -T prefix -N "enter copy mode" v copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind-key -T prefix -N "reload tmux configuration" r source-file ~/.config/tmux/tmux.conf
bind-key -r -T prefix -N "Swap the active pane with the pane above" \{ swap-pane -U
bind-key -r -T prefix -N "Swap the active pane with the pane below" \} swap-pane -D
bind-key -r -T prefix -N "Select the next window" n next-window
bind-key -r -T prefix -N "Select the previous window" p previous-window
bind-key -r -T prefix -N "select next pane" g next-pane

set -g status-left-length 30
set -g status-left-style 'fg=black bg=white'
set -g status-left '#{session_name}#{?session_many_attached,#{session_attached},}'

#           
#        
# 󰈈 󰎂 󱀅 󰓦 󰓹    󰨤 󰃃 󰛐 󱈸  󰝟

set -g status-right-style 'fg=black bg=red'
set -g status-right '%H:%M#[fg=red]#{?client_prefix,#[bg=yellow],#[bg=green]}#[fg=black]%d.%m.%Y'

set -g status-style 'fg=green bg=black'

set -g window-status-current-style 'fg=black bg=green'
# set -g window-status-current-format '#I#W #{s/\*/󰎂 /:window_flags}'

set -g window-status-separator ''
set -g window-status-style 'fg=black bg=colour236'
set -g window-status-current-format '#{?window_bell_flag,#[bg=red],}#{?window_last_flag,#[bg=darkgreen],}#{?window_flags,#I,#[fg=white]#I#[fg=default]#[fg=white]}#W#{?window_flags, ,}#{?window_active,󰎂 ,}#{?window_last_flag, ,}#{?window_marked_flag,󰃃 ,}#{?window_activity_flag, ,}#{?window_bell_flag, ,}#{?window_silence_flag,󰝟 ,}#{?window_zoomed_flag,󰨤 ,}#[fg=default]'
set -g window-status-format '#{?window_bell_flag,#[bg=red],}#{?window_last_flag,#[bg=darkgreen],}#{?window_flags,#I,#[fg=white]#I#[fg=default]#[fg=white]}#W#{?window_flags, ,}#{?window_active,󰎂 ,}#{?window_last_flag, ,}#{?window_marked_flag,󰃃 ,}#{?window_activity_flag, ,}#{?window_bell_flag, ,}#{?window_silence_flag,󰝟 ,}#{?window_zoomed_flag,󰨤 ,}#[fg=default]'

set -g pane-active-border-style 'bg=default,fg=green'
set -g pane-border-style 'bg=default,fg=darkgreen'

set -g pane-border-status 'top'
set -g pane-border-format '#[reverse]#{pane_index}#[noreverse] #{pane_current_command} #[reverse] #[noreverse]'

# automagically install tmux plugin manager
run-shell '/usr/bin/env bash -c "[ -d ~/.config/tmux/plugins ] || mkdir ~/.config/tmux/plugins && [ -d ~/.config/tmux/plugins/tpm ] || git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm"'
run '~/.config/tmux/plugins/tpm/tpm'
